name: MongoDB Integration
on:
  push:
    branches: [main]

jobs:
  mongodb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: DB pusher
        working-directory: ./.github/actions/db-pusher
        run: |
          npm install
          node app.js
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}

      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "prompt_bot"
          author_email: actions@github.com
          message: adding unique id to the metadata
          add: promptify/prompts/text2text
